[project]
name = "nonebot-plugin-kawaii-robot"
version = "3.3.2"
description = "使用 Kyomotoi/AnimeThesaurus 的 NoneBot2 的回复（文i）插件"
authors = [{ name = "karisaya", email = "1048827424@qq.com" }]
dependencies = [
    "nonebot2>=2.0.0",
    "nonebot-adapter-onebot>=2.2.0",
    "pydantic>=1.10.4",
    "anyio>=3.7.1",
]
requires-python = ">=3.8,<4.0"
readme = "README.md"
license = { text = "AGPL-3.0" }

[project.urls]
homepage = "https://github.com/KarisAya/nonebot_plugin_kawaii_robot/"

[project.optional-dependencies]
dev = [
    # 环境
    "pip>=23.0.1",
    "setuptools>=67.6.1",
    "nb-cli>=1.0.5",
    # 工具
    "black>=23.3.0",
    "ruff>=0.0.260",
    "isort>=5.12.0",
]

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
